INSERT INTO product (name, price, quantity, description, created_at)
VALUES ('Baseball Glove', 45.99, 60, 'Premium leather baseball glove for all positions.', NOW()),
       ('Golf Club Set', 399.99, 20, 'Complete golf club set with bag and accessories.', NOW()),
       ('Football Helmet', 150.00, 40, 'High-impact resistant football helmet with faceguard.', NOW()),
       ('Hockey Stick', 59.99, 80, 'Lightweight composite hockey stick for optimal performance.', NOW()),
       ('Swimming Goggles', 19.99, 120, 'Anti-fog swimming goggles with UV protection.', NOW()),
       ('Volleyball', 22.99, 110, 'Official size and weight volleyball for all levels.', NOW()),
       ('Boxing Gloves', 35.99, 90, 'Durable boxing gloves with extra padding.', NOW()),
       ('Treadmill', 999.99, 15, 'High-performance treadmill with multiple workout programs.', NOW()),
       ('Dumbbell Set', 79.99, 75, 'Adjustable dumbbell set for varied strength training.', NOW()),
       ('Bicycle Helmet', 45.99, 130, 'Lightweight bicycle helmet with excellent ventilation.', NOW()),
       ('Jump Rope', 9.99, 200, 'Adjustable speed jump rope for cardio workouts.', NOW()),
       ('Kayak', 499.99, 10, 'Durable kayak suitable for lakes and rivers.', NOW()),
       ('Climbing Rope', 79.99, 25, 'High-strength climbing rope for safety and performance.', NOW()),
       ('Skateboard', 49.99, 60, 'Sturdy skateboard with non-slip deck and smooth wheels.', NOW()),
       ('Surfboard', 299.99, 20, 'High-performance surfboard for waves of all sizes.', NOW()),
       ('Fishing Rod', 59.99, 50, 'Flexible fishing rod with high sensitivity.', NOW()),
       ('Snowboard', 349.99, 25, 'Durable snowboard for all-mountain riding.', NOW()),
       ('Rollerblades', 89.99, 40, 'Comfortable rollerblades with smooth bearings.', NOW()),
       ('Cricket Bat', 39.99, 70, 'Lightweight cricket bat with excellent balance.', NOW()),
       ('Lacrosse Stick', 49.99, 55, 'Durable lacrosse stick with great handling.', NOW()),
       ('Diving Fins', 29.99, 100, 'Comfortable diving fins with strong propulsion.', NOW()),
       ('Archery Bow', 199.99, 15, 'Precision archery bow with adjustable draw weight.', NOW()),
       ('Rowing Machine', 699.99, 10, 'High-quality rowing machine for full-body workouts.', NOW()),
       ('Ping Pong Table', 399.99, 8, 'Sturdy ping pong table with smooth surface.', NOW()),
       ('Kettlebell', 29.99, 80, 'Versatile kettlebell for various strength exercises.', NOW()),
       ('Elliptical Machine', 799.99, 12, 'Smooth and quiet elliptical machine with digital display.', NOW()),
       ('Camping Tent', 149.99, 30, 'Spacious and weather-resistant camping tent.', NOW()),
       ('Sleeping Bag', 59.99, 100, 'Warm and lightweight sleeping bag for all seasons.', NOW()),
       ('Hiking Boots', 99.99, 50, 'Durable hiking boots with excellent grip.', NOW()),
       ('Tennis Balls (Pack of 3)', 7.99, 200, 'High-performance tennis balls with consistent bounce.', NOW()),
       ('Baseball Bat', 29.99, 75, 'Balanced baseball bat for powerful swings.', NOW()),
       ('Boxing Punching Bag', 129.99, 20, 'Heavy-duty punching bag for intense training.', NOW()),
       ('Soccer Goal', 199.99, 15, 'Sturdy soccer goal for practice and games.', NOW()),
       ('Badminton Racket', 24.99, 60, 'Lightweight badminton racket with high control.', NOW()),
       ('Martial Arts Gi', 49.99, 30, 'Comfortable and durable martial arts gi.', NOW()),
       ('Gymnastics Mat', 89.99, 25, 'Thick and supportive gymnastics mat for safe training.', NOW()),
       ('Cycling Gloves', 19.99, 120, 'Breathable cycling gloves with padded palms.', NOW()),
       ('Parachute', 499.99, 5, 'High-quality parachute for skydiving.', NOW()),
       ('Weightlifting Belt', 29.99, 40, 'Supportive weightlifting belt for heavy lifting.', NOW()),
       ('Yoga Blocks', 12.99, 80, 'Foam yoga blocks for support and stability.', NOW()),
       ('Resistance Bands', 19.99, 150, 'Set of resistance bands for strength training.', NOW()),
       ('Punch Mitts', 25.99, 50, 'Durable punch mitts for boxing training.', NOW()),
       ('Ski Poles', 39.99, 35, 'Lightweight ski poles with ergonomic grips.', NOW()),
       ('Ice Skates', 79.99, 40, 'Comfortable ice skates with smooth blades.', NOW()),
       ('Softball', 14.99, 90, 'Durable softball with consistent performance.', NOW()),
       ('Water Bottle', 9.99, 200, 'Insulated water bottle to keep drinks cold.', NOW()),
       ('Foam Roller', 24.99, 80, 'High-density foam roller for muscle recovery.', NOW()),
       ('Golf Balls (Pack of 12)', 29.99, 100, 'High-quality golf balls for consistent performance.', NOW()),
       ('Tennis Bag', 49.99, 30, 'Spacious tennis bag with multiple compartments.', NOW()),
       ('Hiking Backpack', 89.99, 25, 'Durable hiking backpack with large capacity.', NOW());
